// lib/popular-artists.ts

export const POPULAR_ARTISTS_POOL = [
  "Depeche Mode",
  "Radiohead",
  "LCD Soundsystem",
  "Fujiya & Miyagi",
  "Pink Floyd",
  "Suede",
  "Queen",
  "David Bowie",
  "Led Zeppelin",
  "Haruomi Hosono",
  "The Rolling Stones",
  "Bob Dylan",
  "Arctic Monkeys",
  "Tame Impala",
  "The Strokes",
  "Fleetwood Mac",
  "Prince",
  "Daft Punk",
  "The Smiths",
  "Joy Division",
  "Michael Jackson",
  "Frank Ocean",
  "The Weeknd",
  "J. Cole",
  "Travis Scott",
  "Post Malone",
  "Leonard Cohen",
  "Billie Eilish",
  "Olivia Rodrigo",
  "Dua Lipa",
  "Marie Davidson",
  "SZA",
  "Shrag",
  "The Cure",
  "Manic Street Preachers",
  "New Order",
  "Talking Heads",
  "First Aid Kit",
  "Pixies",
  "Clock DVA",
  "Sonic Youth",
  "My Bloody Valentine",
  "Beach House",
  "MGMT",
  "Pulp",
  "Metallica",
  "AC/DC",
  "Miles Davis",
  "John Coltrane",
  "Charles Mingus",
  "Thelonious Monk",
  "Bill Evans",
  "Aphex Twin",
  "Boards of Canada",
  "Four Tet",
  "Burial",
  "Flying Lotus",
  "MF DOOM",
  "Madlib",
  "Nirvana",
  "A Tribe Called Quest",
  "Wu-Tang Clan",
  "Nas",
  "Björk",
  "Portishead",
  "Massive Attack",
  "Thom Yorke",
  "Nick Cave",
  "The National",
  "Death Cab for Cutie",
  "Vampire Weekend",
  "Fleet Foxes",
  "Kid Francescoli",
  "Bon Iver",
  "Sufjan Stevens",
  "Elliott Smith",
  "Neil Young",
  "The Clash",
  "Sex Pistols",
  "Kraftwerk",
  "Can",
  "Neu!",
  "Brian Eno",
  "David Byrne",
  "Marvin Gaye",
  "Curtis Mayfield",
  "Cabaret Voltaire",
  "James Brown",
  "Aretha Franklin",
  "The Velvet Underground",
  "Television",
  "Iggy Pop",
  "Lou Reed",
  "Pigbag",
  "Calvin Harris",
  "Charli XCX",
  "D-Block Europe",
  "The Kooks",
  "NewJeans",
  "Public Enemy",
  "Sam Cooke",
  "The Beatles",
  "Missy Elliott",
  "Outkast",
  "The Beach Boys",
  "Stevie Wonder",
  "The Kinks",
  "Beyoncé",
  "Prince and the Revolution",
  "John Lennon",
  "Robyn",
  "Billie Holiday",
  "The Ronettes",
  "Kanye West",
  "Joni Mitchell",
  "Bruce Springsteen",
  "Dr. Dre",
  "Lorde",
  "The Notorious B.I.G.",
  "Chuck Berry",
  "Little Richard",
  "The White Stripes",
  "Otis Redding",
  "The Jimi Hendrix Experience",
  "Bob Marley and the Wailers",
  "The Temptations",
  "Kendrick Lamar",
  "M.I.A.",
  "Elton John",
  "Lauryn Hill",
  "Daddy Yankee",
  "Dionne Warwick",
  "Donna Summer",
  "Smokey Robinson and the Miracles",
  "Madonna",
  "Sly and the Family Stone",
  "The Band",
  "Grandmaster Flash and the Furious Five",
  "Kate Bush",
  "U2",
  "Dolly Parton",
  "Ramones",
  "Earth, Wind and Fire",
  "Simon and Garfunkel",
  "Chic",
  "Taylor Swift",
  "Elvis Presley",
  "Tracy Chapman",
  "Johnny Cash",
  "The Modern Lovers",
  "The Four Tops",
  "Amy Winehouse",
  "Ray Charles",
  "Adele",
  "Al Green",
  "Guns N’ Roses",
  "UGK",
  "Kelly Clarkson",
  "Whitney Houston",
  "Oasis",
  "Jay-Z",
  "Patti Smith",
  "Bee Gees",
  "Yeah Yeah Yeahs",
  "Alanis Morissette",
  "The Jackson 5",
  "R.E.M.",
  "Britney Spears",
  "Etta James",
  "X-Ray Spex",
  "The Impressions",
  "Buddy Holly",
  "George Michael",
  "TLC",
  "Drake",
  "Martha and the Vandellas",
  "Ben E. King",
  "Eric B. and Rakim",
  "Journey",
  "Tina Turner",
  "Ariana Grande",
  "The Sounds",
  "Blondie",
  "Rod Stewart",
  "George Jones",
  "James Taylor",
  "Fats Domino",
  "Green Day",
  "The Shirelles",
  "Creedence Clearwater Revival",
  "Rick James",
  "Howlin’ Wolf",
  "The Kingsmen",
  "The Meters",
  "The Who",
  "Nick Drake",
  "Hank Williams",
  "Mott the Hoople",
  "Eminem",
  "Dusty Springfield",
  "Tom Petty and the Heartbreakers",
  "The Five Satins",
  "Louis Armstrong",
  "Nina Simone",
  "The Flamingos",
  "Van Halen",
  "The Byrds",
  "Sinéad O’Connor",
  "The Staple Singers",
  "N.W.A",
  "Bobbie Gentry",
  "Geto Boys",
  "PJ Harvey",
  "Patsy Cline",
  "Ann Peebles",
  "Aerosmith",
  "Glen Campbell",
  "Rage Against the Machine",
  "Hole",
  "Don Henley",
  "Funkadelic",
  "Boston",
  "Steely Dan",
  "Mobb Deep",
  "Stevie Nicks",
  "Wilson Pickett",
  "Tom Petty",
  "Ike and Tina Turner",
  "Crosby, Stills, Nash and Young",
  "Derek and the Dominos",
  "Woody Guthrie",
  "Deee-Lite",
  "The Supremes",
  "Bill Withers",
  "Aaliyah",
  "Big Star",
  "Backstreet Boys",
  "Digital Underground",
  "Jerry Lee Lewis",
  "Pavement",
  "Beastie Boys",
  "Faces",
  "Joan Jett",
  "Gloria Gaynor",
  "Parliament",
  "Willie Nelson",
  "Loretta Lynn",
  "Martha Reeves and the Vandellas",
  "Gil-Scott Heron",
  "The Wailers",
  "Paul Simon",
  "The Replacements",
  "Augustus Pablo",
  "The Isley Brothers",
  "The Righteous Brothers",
  "Nine Inch Nails",
  "Procol Harum",
  "Thin Lizzy",
  "Roberta Flack",
  "Randy Newman",
  "Buzzcocks",
  "Bo Diddley",
  "Toots and the Maytals",
  "BTS",
  "Clipse",
  "INXS",
  "Destiny’s Child",
  "ABBA",
  "The Funky 4 + 1",
  "Usher",
  "Phil Collins",
  "Alice Cooper",
  "Bikini Kill",
  "Screamin’ Jay Hawkins",
  "The B-52’s",
  "Bob Seger",
  "The Police",
  "Gnarls Barkley",
  "Liz Phair",
  "The Doors",
  "The Eagles",
  "Isaac Hayes",
  "The Stooges",
  "The Shangri-Las",
  "Big Mama Thornton",
  "Tears for Fears",
  "2Pac",
  "Everly Brothers",
  "Billy Joel",
  "Rilo Kiley",
  "Mary J. Blige",
  "Red Hot Chili Peppers",
  "Bad Bunny",
  "The Marvelettes",
  "Rihanna",
  "The Grateful Dead",
  "Marshall Jefferson",
  "Hall & Oates",
  "Cher",
  "Black Sabbath",
  "The Monkees",
  "The Doobie Brothers",
  "Carole King",
  "Roxy Music",
  "The Zombies",
  "John Prine",
  "Jorge Ben",
  "Ice Cube",
  "Eurythmics",
  "Thelma Houston",
  "Cheap Trick",
  "Fugees",
  "Jimmy Cliff",
  "Kacey Musgraves",
  "The Crystals",
  "Soundgarden",
  "The Cars",
  "Bonnie Raitt",
  "William DeVaughn",
  "The Drifters",
  "Merle Haggard",
  "The Killers",
  "D’Angelo",
  "Fountains of Wayne",
  "The Slits",
  "Fiona Apple",
  "Childish Gambino",
  "Cardi B",
  "Diana Ross",
  "New York Dolls",
  "DMX",
  "Pretenders",
  "Eric Church",
  "Jeff Buckley",
  "Soulsonic Force",
  "Elvis Costello",
  "Duran Duran",
  "Sylvester",
  "Kiss",
  "Selena",
  "Run-DMC",
  "Lynyrd Skynyrd",
  "Yusuf / Cat Stevens",
  "Foo Fighters",
  "Allman Brothers Band",
  "Wilco",
  "Neneh Cherry",
  "Them",
  "Wizkid",
  "Pearl Jam",
  "Mark Ronson",
  "Booker T. & the M.G.'s",
  "Mariah Carey",
  "The Mamas and the Papas",
  "Craig Mack",
  "Blackstreet",
  "Muddy Waters",
  "Nicki Minaj",
  "Sugar Hill Gang",
  "Pete Rock & CL Smooth",
  "Eddie Cochran",
  "Pet Shop Boys",
  "Rush",
  "Carly Rae Jepsen",
  "Lucinda Williams",
  "Megan Thee Stallion",
  "Celia Cruz",
  "Alicia Keys",
  "Miranda Lambert",
  "Motörhead",
  "Fall Out Boy",
  "50 Cent",
  "T. Rex",
  "Erykah Badu",
  "Blue Öyster Cult",
  "Migos",
  "Toto",
  "Sister Nancy",
  "Jefferson Airplane",
  "Lana Del Rey",
  "Bon Jovi",
  "Beck",
  "Sade",
  "Steel Pulse",
  "Roy Orbison",
  "Van Morrison",
  "John Lee Hooker",
  "Luther Vandross",
  "Mazzy Star",
  "Dixie Chicks",
  "Gladys Knight and the Pips",
  "The Animals",
  "Peter Gabriel",
  "Tammy Wynette",
  "Janet Jackson",
  "Kris Kristofferson",
  "The Go-Gos",
  "Juvenile",
  "Santana",
  "Biz Markie",
  "Robert Johnson",
  "Lady Gaga",
  "Weezer",
  "Azealia Banks",
  "Lil Wayne",
  "Solange",
  "The Breeders",
  "Lil Nas X",
  "Cyndi Lauper",
  "Carly Simon",
  "Harry Nilsson",
  "Lizzo",
  "Townes Van Zandt",
  "Harry Styles",
];
